import { library } from '@fortawesome/fontawesome-svg-core';
import {
    faPencilAlt,
    faMoneyBillAlt,
    faFileInvoiceDollar,
    faChartLine,
    faShoppingCart,
    faHandHoldingUsd,
    faArrowLeft,
    faCashRegister,
    faClipboardList,
    faClipboard,
    faUserPlus,
    faPlusCircle,
    faExternalLinkAlt,
    faEdit,
    faSearch,
    faSave,
    faTrashAlt,
    faCheck,
    faTimes
} from '@fortawesome/free-solid-svg-icons';

library.add(
    faPencilAlt,
    faMoneyBillAlt,
    faFileInvoiceDollar,
    faChartLine,
    faShoppingCart,
    faShoppingCart,
    faHandHoldingUsd,
    faArrowLeft,
    faCashRegister,
    faClipboardList,
    faClipboard,
    faUserPlus,
    faPlusCircle,
    faExternalLinkAlt,
    faEdit,
    faSearch,
    faSave,
    faTrashAlt,
    faCheck,
    faTimes
);